In [170]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [171]:
df_dataworld = pd.read_excel('Final_Project_Internet_Dataset.xlsx')
df_dataworld.head()

,Source.Name,COMMENT_ID,AUTHOR,DATE,CONTENT,CLASS
0,Youtube01-Psy.csv,LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU,Julius NM,2013-11-07 06:20:48,"Huh, anyway check out this you[tube] channel: ...",1.0
1,Youtube01-Psy.csv,LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A,adam riyati,2013-11-07 12:37:15,Hey guys check out my new channel and our firs...,1.0
2,Youtube01-Psy.csv,LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8,Evgeny Murashkin,2013-11-08 17:34:21,just for test I have to say murdev.com,1.0
3,Youtube01-Psy.csv,z13jhp0bxqncu512g22wvzkasxmvvzjaz04,ElNino Melendez,2013-11-09 08:28:43,me shaking my sexy ass on my channel enjoy ^_^ ﻿,1.0
4,Youtube01-Psy.csv,z13fwbwp1oujthgqj04chlngpvzmtt3r3dw,GsMega,2013-11-10 16:05:38,watch?v=vtaRGgvGtWQ Check this out .﻿,1.0

In [172]:
df_dataworld_small = df_dataworld[['CONTENT','CLASS']]
df_dataworld_small.head()

                                             CONTENT  CLASS
0  Huh, anyway check out this you[tube] channel: ...    1.0
1  Hey guys check out my new channel and our firs...    1.0
2             just for test I have to say murdev.com    1.0
3   me shaking my sexy ass on my channel enjoy ^_^ ﻿    1.0
4            watch?v=vtaRGgvGtWQ   Check this out .﻿    1.0

In [173]:
df_dataworld_small["CLASS"] = df_dataworld_small["CLASS"].replace(to_replace=1.0, value=True)
df_dataworld_small["CLASS"] = df_dataworld_small["CLASS"].replace(to_replace=0.0, value=False)
df_dataworld_small

C:\Users\jckc1\AppData\Local\Temp\ipykernel_21392\397476993.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dataworld_small["CLASS"] = df_dataworld_small["CLASS"].replace(to_replace=1.0, value=True)
C:\Users\jckc1\AppData\Local\Temp\ipykernel_21392\397476993.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dataworld_small["CLASS"] = df_dataworld_small["CLASS"].replace(to_replace=0.0, value=False)

                                                CONTENT  CLASS
0     Huh, anyway check out this you[tube] channel: ...   True
1     Hey guys check out my new channel and our firs...   True
2                just for test I have to say murdev.com   True
3      me shaking my sexy ass on my channel enjoy ^_^ ﻿   True
4               watch?v=vtaRGgvGtWQ   Check this out .﻿   True
...                                                 ...    ...
1956  I love this song because we sing it at Camp al...  False
1957  I love this song for two reasons: 1.it is abou...  False
1958                                                wow  False
1959                            Shakira u are so wiredo  False
1960                         Shakira is the best dancer  False

[1961 rows x 2 columns]

In [174]:
df_collected = pd.read_excel('Final Project Full Collected Dataset.xlsx')
df_collected.head()

,Source.Name,author,updated_at,like_count,text,class
0,AFA.csv,@AustorFIFA,2024-11-18 15:44:00,19,*Like & SIUUUUbscribe* to keep yourself up to ...,False
1,AFA.csv,@dawnkuppan,2024-11-19 13:40:41,0,Ronaldo going back to sporting Lisbon for one ...,False
2,AFA.csv,@eesa5204,2024-11-19 13:32:54,0,Any1 gonna talk about zirkzee,False
3,AFA.csv,@ThatRelevantDude,2024-11-19 12:32:03,0,YES BRO 524 SUBS,False
4,AFA.csv,@mariussilahviravong4231,2024-11-19 11:11:24,0,W video,False

In [175]:
df_collected_small= df_collected[["text","class"]]
df_collected_small

                                                   text  class
0     *Like & SIUUUUbscribe* to keep yourself up to ...  False
1     Ronaldo going back to sporting Lisbon for one ...  False
2                         Any1 gonna talk about zirkzee  False
3                                      YES BRO 524 SUBS  False
4                                               W video  False
...                                                 ...    ...
5776                                                Uwu  False
5777  My way is the editor. I know it's questionable...  False
5778                                       pls teach me  False
5779                              Saving all the saves!  False
5780                                         First like  False

[5781 rows x 2 columns]

In [176]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
#nltk.download("punkt")
#nltk.download("stopwords")
stop_words = set(stopwords.words("english"))

In [177]:
df_dataworld_small["clean_text"] = df_dataworld_small["CONTENT"].apply(word_tokenize)

C:\Users\jckc1\AppData\Local\Temp\ipykernel_21392\4090385540.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dataworld_small["clean_text"] = df_dataworld_small["CONTENT"].apply(word_tokenize)

In [178]:
for i in range(len(df_dataworld_small["clean_text"])):
    df_dataworld_small["clean_text"][i] = [word for word in df_dataworld_small["clean_text"][i] if word.lower() not in stop_words]

C:\Users\jckc1\AppData\Local\Temp\ipykernel_21392\920118193.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dataworld_small["clean_text"][i] = [word for word in df_dataworld_small["clean_text"][i] if word.lower() not in stop_words]

In [179]:
for i in range(len(df_dataworld_small["clean_text"])):
    df_dataworld_small["clean_text"][i] = " ".join(df_dataworld_small["clean_text"][i])

C:\Users\jckc1\AppData\Local\Temp\ipykernel_21392\1175050482.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dataworld_small["clean_text"][i] = " ".join(df_dataworld_small["clean_text"][i])

In [180]:
df_dataworld_small

,CONTENT,CLASS,clean_text
0,"Huh, anyway check out this you[tube] channel: ...",True,"Huh , anyway check [ tube ] channel : kobyoshi02"
1,Hey guys check out my new channel and our firs...,True,Hey guys check new channel first vid US MONKEY...
2,just for test I have to say murdev.com,True,test say murdev.com
3,me shaking my sexy ass on my channel enjoy ^_^ ﻿,True,shaking sexy ass channel enjoy ^_^ ﻿
4,watch?v=vtaRGgvGtWQ Check this out .﻿,True,watch ? v=vtaRGgvGtWQ Check .﻿
...,...,...,...
1956,I love this song because we sing it at Camp al...,False,love song sing Camp time ! !
1957,I love this song for two reasons: 1.it is abou...,False,love song two reasons : 1.it Africa 2.i born b...
1958,wow,False,wow
1959,Shakira u are so wiredo,False,Shakira u wiredo
1960,Shakira is the best dancer,False,Shakira best dancer

In [181]:
df_collected_small.head()

                                                text  class
0  *Like & SIUUUUbscribe* to keep yourself up to ...  False
1  Ronaldo going back to sporting Lisbon for one ...  False
2                      Any1 gonna talk about zirkzee  False
3                                   YES BRO 524 SUBS  False
4                                            W video  False

In [182]:
for i in range(len(df_collected_small["text"])):
    df_collected_small["text"][i] = str(df_collected_small["text"][i])

C:\Users\jckc1\AppData\Local\Temp\ipykernel_21392\3111001044.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_collected_small["text"][i] = str(df_collected_small["text"][i])

In [183]:
df_collected_small["clean_text"] = df_collected_small["text"].apply(word_tokenize)

C:\Users\jckc1\AppData\Local\Temp\ipykernel_21392\1727650808.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_collected_small["clean_text"] = df_collected_small["text"].apply(word_tokenize)

In [184]:
for i in range(len(df_collected_small["clean_text"])):
    df_collected_small["clean_text"][i] = [word for word in df_collected_small["clean_text"][i] if word.lower() not in stop_words]

C:\Users\jckc1\AppData\Local\Temp\ipykernel_21392\1807987973.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_collected_small["clean_text"][i] = [word for word in df_collected_small["clean_text"][i] if word.lower() not in stop_words]

In [185]:
for i in range(len(df_collected_small["clean_text"])):
    df_collected_small["clean_text"][i] = " ".join(df_collected_small["clean_text"][i])

C:\Users\jckc1\AppData\Local\Temp\ipykernel_21392\4053694348.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_collected_small["clean_text"][i] = " ".join(df_collected_small["clean_text"][i])

In [186]:
df_collected_small

,text,class,clean_text
0,*Like & SIUUUUbscribe* to keep yourself up to ...,False,* Like & SIUUUUbscribe * keep date Football Tr...
1,Ronaldo going back to sporting Lisbon for one ...,False,Ronaldo going back sporting Lisbon one last da...
2,Any1 gonna talk about zirkzee,False,Any1 gon na talk zirkzee
3,YES BRO 524 SUBS,False,YES BRO 524 SUBS
4,W video,False,W video
...,...,...,...
5776,Uwu,False,Uwu
5777,My way is the editor. I know it's questionable...,False,way editor . know 's questionable way everyone...
5778,pls teach me,False,pls teach
5779,Saving all the saves!,False,Saving saves !
5780,First like,False,First like

In [187]:
df_collected_final = df_collected_small[["clean_text", "class"]]
df_collected_final.head()

                                          clean_text  class
0  * Like & SIUUUUbscribe * keep date Football Tr...  False
1  Ronaldo going back sporting Lisbon one last da...  False
2                           Any1 gon na talk zirkzee  False
3                                   YES BRO 524 SUBS  False
4                                            W video  False

In [188]:
df_dataworld_final = df_dataworld_small[["clean_text", "CLASS"]]
df_dataworld_final.columns = ["clean_text", "class"]
df_dataworld_final.head()

                                          clean_text class
0   Huh , anyway check [ tube ] channel : kobyoshi02  True
1  Hey guys check new channel first vid US MONKEY...  True
2                                test say murdev.com  True
3               shaking sexy ass channel enjoy ^_^ ﻿  True
4                     watch ? v=vtaRGgvGtWQ Check .﻿  True

In [189]:
df_combined_data = pd.concat([df_dataworld_final, df_collected_final])
df_combined_data

                                             clean_text  class
0      Huh , anyway check [ tube ] channel : kobyoshi02   True
1     Hey guys check new channel first vid US MONKEY...   True
2                                   test say murdev.com   True
3                  shaking sexy ass channel enjoy ^_^ ﻿   True
4                        watch ? v=vtaRGgvGtWQ Check .﻿   True
...                                                 ...    ...
5776                                                Uwu  False
5777  way editor . know 's questionable way everyone...  False
5778                                          pls teach  False
5779                                     Saving saves !  False
5780                                         First like  False

[7742 rows x 2 columns]

In [190]:
df_combined = df_combined_data.reset_index(drop = True)

In [191]:
## This is where we need to split to recover the original two datasets
df_combined["clean_text"][1961]

'* Like & SIUUUUbscribe * keep date Football Transfers Football News ! _x000D_ _x000D_ 3 Days Ago - > NEW CONFIRMED TRANSFERS & RUMOURS ! - > https : //youtu.be/nVGX5B7y6Zo_x000D_ Confirmed Summer Transfers 2024 - > https : //youtu.be/nTjlLOp5uOw'

In [192]:
## Code from here: https://okan.cloud/posts/2021-04-08-text-vectorization-using-python-term-document-matrix/
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()  
vects = vect.fit_transform(df_combined["clean_text"])

td = pd.DataFrame(vects.todense())
td.columns = vect.get_feature_names_out()
term_document_matrix = td.T
term_document_matrix.columns = ['Doc '+str(i) for i in range(len(df_combined["clean_text"]))]
term_document_matrix['total_count'] = term_document_matrix.sum(axis=1)

term_document_matrix = term_document_matrix.sort_values(by ='total_count',ascending=False)

In [193]:
term_document_matrix

,Doc 0,Doc 1,Doc 2,Doc 3,Doc 4,Doc 5,Doc 6,Doc 7,Doc 8,Doc 9,...,Doc 7733,Doc 7734,Doc 7735,Doc 7736,Doc 7737,Doc 7738,Doc 7739,Doc 7740,Doc 7741,total_count
video,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,611
like,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,610
check,1,1,0,0,1,1,0,1,1,1,...,0,0,0,0,0,0,0,0,0,590
love,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,505
please,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
mud,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
d3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
mu,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
d4aaacwk,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
𝚟𝚒𝚎𝚠,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [194]:
term_document_matrix = term_document_matrix.drop("total_count",axis = 1)
document_term_matrix = term_document_matrix.T
document_term_matrix

,video,like,check,love,please,game,one,song,com,youtube,...,d15fb87973,mullet,muller,muito,d22,mud,d3,mu,d4aaacwk,𝚟𝚒𝚎𝚠
Doc 0,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Doc 1,0,1,1,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Doc 2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
Doc 3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Doc 4,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Doc 7737,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Doc 7738,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Doc 7739,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Doc 7740,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Doc 7741,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [195]:
counts = pd.DataFrame([(document_term_matrix!=0).sum(1)]).T
counts

           0
Doc 0      6
Doc 1     17
Doc 2      4
Doc 3      5
Doc 4      3
...       ..
Doc 7737   1
Doc 7738  17
Doc 7739   2
Doc 7740   2
Doc 7741   2

[7742 rows x 1 columns]

In [196]:
NMatrix=np.ones(np.shape(document_term_matrix), dtype=float)*len(document_term_matrix["video"])
print(NMatrix)

[[7742. 7742. 7742. ... 7742. 7742. 7742.]
 [7742. 7742. 7742. ... 7742. 7742. 7742.]
 [7742. 7742. 7742. ... 7742. 7742. 7742.]
 ...
 [7742. 7742. 7742. ... 7742. 7742. 7742.]
 [7742. 7742. 7742. ... 7742. 7742. 7742.]
 [7742. 7742. 7742. ... 7742. 7742. 7742.]]

In [197]:
IDF = np.log2(np.divide(NMatrix, np.array(counts)))
IDF

C:\Users\jckc1\AppData\Local\Temp\ipykernel_21392\3792717648.py:1: RuntimeWarning: divide by zero encountered in divide
  IDF = np.log2(np.divide(NMatrix, np.array(counts)))

array([[10.33352809, 10.33352809, 10.33352809, ..., 10.33352809,
        10.33352809, 10.33352809],
       [ 8.83102775,  8.83102775,  8.83102775, ...,  8.83102775,
         8.83102775,  8.83102775],
       [10.91849059, 10.91849059, 10.91849059, ..., 10.91849059,
        10.91849059, 10.91849059],
       ...,
       [11.91849059, 11.91849059, 11.91849059, ..., 11.91849059,
        11.91849059, 11.91849059],
       [11.91849059, 11.91849059, 11.91849059, ..., 11.91849059,
        11.91849059, 11.91849059],
       [11.91849059, 11.91849059, 11.91849059, ..., 11.91849059,
        11.91849059, 11.91849059]])

In [198]:
tfidf_data = document_term_matrix * IDF
tfidf_data

,video,like,check,love,please,game,one,song,com,youtube,...,d15fb87973,mullet,muller,muito,d22,mud,d3,mu,d4aaacwk,𝚟𝚒𝚎𝚠
Doc 0,0.0,0.000000,10.333528,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Doc 1,0.0,8.831028,8.831028,0.0,17.662056,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Doc 2,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,10.918491,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Doc 3,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Doc 4,0.0,0.000000,11.333528,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Doc 7737,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Doc 7738,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Doc 7739,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Doc 7740,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Doc 7741,0.0,11.918491,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [199]:
tfidf_class = df_combined["class"]
tfidf_class.head()

0    True
1    True
2    True
3    True
4    True
Name: class, dtype: object

In [200]:
tfidf_list = list(tfidf_class)
tfidf_classlist = []
for i in tfidf_list:
    if i == True:
        tfidf_classlist.append("True")
    else:
        tfidf_classlist.append("False")

In [201]:
df_document_dataframe = tfidf_data
df_document_dataframe["spam_class"] = tfidf_classlist
df_document_dataframe

,video,like,check,love,please,game,one,song,com,youtube,...,mullet,muller,muito,d22,mud,d3,mu,d4aaacwk,𝚟𝚒𝚎𝚠,spam_class
Doc 0,0.0,0.000000,10.333528,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,True
Doc 1,0.0,8.831028,8.831028,0.0,17.662056,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,True
Doc 2,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,10.918491,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,True
Doc 3,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,True
Doc 4,0.0,0.000000,11.333528,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Doc 7737,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
Doc 7738,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
Doc 7739,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
Doc 7740,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False
Doc 7741,0.0,11.918491,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False

In [203]:
df_document_dataframe.to_csv('Final Project Dataset.csv')